In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
heart_df=pd.read_csv('heart.csv')
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [6]:
heart_df.sample(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
548,66,M,ASY,112,261,0,Normal,140,N,1.5,Up,1
373,59,M,ASY,135,0,0,Normal,115,Y,1.0,Flat,1
909,63,F,ASY,124,197,0,Normal,136,Y,0.0,Flat,1
552,71,M,NAP,144,221,0,Normal,108,Y,1.8,Flat,1
21,44,M,ATA,120,184,0,Normal,142,N,1.0,Flat,0

In [7]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [8]:
heart_df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [9]:
heart_df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

Data preprocessing

In [10]:
##checking null values
heart_df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [11]:
heart_df.duplicated().sum()

np.int64(0)

In [12]:
heart_df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [13]:
heart_df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [14]:
cat_col=heart_df.select_dtypes(include='object').columns

In [15]:
range(heart_df['ChestPainType'].nunique())

range(0, 4)

In [16]:
for col in cat_col:
    print(col)
    print(heart_df[col].unique()),list(range(heart_df[col].nunique()))
    heart_df[col].replace((heart_df[col].unique()),range(heart_df[col].nunique()),inplace=True)
    print('*'*90)
    print()

Sex
['M' 'F']
******************************************************************************************

ChestPainType
['ATA' 'NAP' 'ASY' 'TA']
******************************************************************************************

RestingECG
['Normal' 'ST' 'LVH']
******************************************************************************************

ExerciseAngina
['N' 'Y']
******************************************************************************************

ST_Slope
['Up' 'Flat' 'Down']
******************************************************************************************

In [17]:
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,0,140,289,0,0,172,0,0.0,0,0
1,49,1,1,160,180,0,0,156,0,1.0,1,1
2,37,0,0,130,283,0,1,98,0,0.0,0,0
3,48,1,2,138,214,0,0,108,1,1.5,1,1
4,54,0,1,150,195,0,0,122,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,3,110,264,0,0,132,0,1.2,1,1
914,68,0,2,144,193,1,0,141,0,3.4,1,1
915,57,0,2,130,131,0,0,115,1,1.2,1,1
916,57,1,0,130,236,0,2,174,0,0.0,1,1
917,38,0,1,138,175,0,0,173,0,0.0,0,0

In [18]:
heart_df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
220     10
223     10
204      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

Imputing the 0 values in cholestrol column with KNN imputer

In [19]:
np.nan

nan

In [20]:
heart_df['Cholesterol'].replace(0,np.nan,inplace=True)

In [21]:
heart_df['Cholesterol'].isna().sum()

np.int64(172)

In [22]:


from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=3)
after_impute=imputer.fit_transform(heart_df)
heart_df=pd.DataFrame(after_impute,columns=heart_df.columns)

In [23]:
count=0
for i in heart_df['Cholesterol']:
    if i==0:
        count+=1
print(count)

0

In [24]:


from sklearn.impute import KNNImputer
heart_df['RestingBP'].replace(0,np.nan,inplace=True)




imputer=KNNImputer(n_neighbors=3)
after_impute=imputer.fit_transform(heart_df)
heart_df=pd.DataFrame(after_impute,columns=heart_df.columns)

In [25]:
heart_df['RestingBP'].unique()

array([140., 160., 130., 138., 150., 120., 110., 136., 115., 100., 124.,
       113., 125., 145., 112., 132., 118., 170., 142., 190., 135., 180.,
       108., 155., 128., 106.,  92., 200., 122.,  98., 105., 133.,  95.,
        80., 137., 185., 165., 126., 152., 116., 144., 154., 134., 104.,
       139., 131., 141., 178., 146., 158., 123., 102.,  96., 143., 172.,
       156., 114., 127., 101., 174.,  94., 148., 117., 192., 129., 164.])

In [26]:
heart_df['RestingBP'].isna().sum()

np.int64(0)

In [27]:
withoutOldPeak=heart_df.columns
withoutOldPeak=withoutOldPeak.drop('Oldpeak')
heart_df[withoutOldPeak]=heart_df[withoutOldPeak].astype('int32')

In [28]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int32
 1   Sex             918 non-null    int32
 2   ChestPainType   918 non-null    int32
 3   RestingBP       918 non-null    int32
 4   Cholesterol     918 non-null    int32
 5   FastingBS       918 non-null    int32
 6   RestingECG      918 non-null    int32
 7   MaxHR           918 non-null    int32
 8   ExerciseAngina  918 non-null    int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int32
 11  HeartDisease    918 non-null    int32
dtypes: float64(1), int32(11)
memory usage: 46.7 KB

Data Visualization

In [29]:
import plotly.express as px

In [30]:
heart_df.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
791,51,0,2,140,298,0,0,122,1,4.2,1,1

In [31]:
heart_df.corr()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Age,1.000000,-0.055750,0.214164,0.263128,0.057108,0.198039,0.213152,-0.382045,0.215793,0.258612,0.268264,0.282039
Sex,-0.055750,1.000000,-0.179766,-0.009658,0.080395,-0.120076,0.018343,0.189186,-0.190664,-0.105734,-0.150693,-0.305445
ChestPainType,0.214164,-0.179766,1.000000,0.073016,0.038855,0.155111,0.112067,-0.273076,0.324049,0.300846,0.352364,0.459017
RestingBP,0.263128,-0.009658,0.073016,1.000000,0.113194,0.067556,0.094144,-0.109329,0.152621,0.174464,0.082401,0.118333
Cholesterol,0.057108,0.080395,0.038855,0.113194,1.000000,0.058798,0.074925,-0.028855,0.083761,0.065988,0.071345,0.101263
FastingBS,0.198039,-0.120076,0.155111,0.067556,0.058798,1.000000,0.050707,-0.131438,0.060451,0.052698,0.175774,0.267291
RestingECG,0.213152,0.018343,0.112067,0.094144,0.074925,0.050707,1.000000,0.048552,0.036119,0.114428,0.078807,0.061011
MaxHR,-0.382045,0.189186,-0.273076,-0.109329,-0.028855,-0.131438,0.048552,1.000000,-0.370425,-0.160691,-0.343419,-0.400421
ExerciseAngina,0.215793,-0.190664,0.324049,0.152621,0.083761,0.060451,0.036119,-0.370425,1.000000,0.408752,0.428706,0.494282
Oldpeak,0.258612,-0.105734,0.300846,0.174464,0.065988,0.052698,0.114428,-0.160691,0.408752,1.000000,0.501921,0.403951
ST_Slope,0.268264,-0.150693,0.352364,0.082401,0.071345,0.175774,0.078807,-0.343419,0.428706,0.501921,1.000000,0.558771
HeartDisease,0.282039,-0.305445,0.459017,0.118333,0.101263,0.267291,0.061011,-0.400421,0.494282,0.403951,0.558771,1.000000

In [32]:
px.line(heart_df.corr()['HeartDisease'][:-1].sort_values())

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'variable=HeartDisease<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'HeartDisease',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines',
              'name': 'HeartDisease',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['MaxHR', 'Sex', 'RestingECG', 'Cholesterol', 'RestingBP', 'FastingBS',
                          'Age', 'Oldpeak', 'ChestPainType', 'ExerciseAngina', 'ST_Slope'],
                         dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('ovJeb36g2b9OojLVaIzTv7rAvnHYPK' ... 'KIYN0/J8R471Ci3z+tvkcfc+HhPw=='),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

Age and HeartDisease Distribution

In [33]:
px.sunburst(heart_df,path=['HeartDisease','Age'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'branchvalues': 'total',
              'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'labels=%{label}<br>count=%{value}<br>parent=%{parent}<br>id=%{id}<extra></extra>',
              'ids': array(['0/40', '1/49', '0/37', '1/48', '0/54', '0/39', '0/45', '1/37', '0/48',
                            '1/58', '0/42', '1/38', '0/43', '1/60', '1/36', '0/44', '0/49', '1/44',
                            '0/36', '0/53', '0/52', '0/51', '1/53', '0/56', '1/54', '1/41', '0/32',
                            '1/65', '0/41', '0/35', '1/43', '0/59', '0/50', '1/50', '1/47', '1/31',
                            '1/52', '1/46', '1/57', '1/55', '0/46', '1/32', '0/55', '1/63', '1/56',
                            '1/66', '1/40', '0/57', '0/34', '0/47', '0/38', '1/33', '1/59', '1/34',
                            '0/58', '0/61', '0/29', '0/62', '0/31', '1/35', '0/28', '0/30', '1/39',
                            '1/51', '0/33', '1/45', '0/60', '1/61', '1/62', '0/65', '1/74', '1/68',
                            '1/42', '0/72', '1/64', '1/69', '1/67', '1/73', '1/70', '0/66', '0/63',
                            '0/74', '1/77', '1/72', '1/75', '0/64', '1/76', '0/68', '1/71', '0/75',
                            '0/69', '0/67', '0/71', '0/70', '0/76', '0', '1'], dtype=object),
              'labels': array(['40', '49', '37', '48', '54', '39', '45', '37', '48', '58', '42', '38',
                               '43', '60', '36', '44', '49', '44', '36', '53', '52', '51', '53', '56',
                               '54', '41', '32', '65', '41', '35', '43', '59', '50', '50', '47', '31',
                               '52', '46', '57', '55', '46', '32', '55', '63', '56', '66', '40', '57',
                               '34', '47', '38', '33', '59', '34', '58', '61', '29', '62', '31', '35',
                               '28', '30', '39', '51', '33', '45', '60', '61', '62', '65', '74', '68',
                               '42', '72', '64', '69', '67', '73', '70', '66', '63', '74', '77', '72',
                               '75', '64', '76', '68', '71', '75', '69', '67', '71', '70', '76', '0',
                               '1'], dtype=object),
              'name': '',
              'parents': array(['0', '1', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1', '0', '1',
                                '1', '0', '0', '1', '0', '0', '0', '0', '1', '0', '1', '1', '0', '1',
                                '0', '0', '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '0', '1',
                                '0', '1', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '0', '0',
                                '0', '0', '0', '1', '0', '0', '1', '1', '0', '1', '0', '1', '1', '0',
                                '1', '1', '1', '0', '1', '1', '1', '1', '1', '0', '0', '0', '1', '1',
                                '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '', ''],
                               dtype=object),
              'type': 'sunburst',
              'values': {'bdata': ('BwALAAoADwAcAA0ADwABABAAHAAPAA' ... 'EABAACAAEAAwADAAMAAQABAJoB/AE='),
                         'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [34]:
px.pie(heart_df,names='HeartDisease',title='precentage of HeartDisease classes classification')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'HeartDisease=%{label}<extra></extra>',
              'labels': {'bdata': ('AAAAAAEAAAAAAAAAAQAAAAAAAAAAAA' ... 'AAAAEAAAABAAAAAQAAAAEAAAAAAAAA'),
                         'dtype': 'i4'},
              'legendgroup': '',
              'name': '',
              'showlegend': True,
              'type': 'pie'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'precentage of HeartDisease classes classification'}}
})

In [35]:
px.histogram(heart_df,x='Age',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>Age=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('KAAAACUAAAA2AAAAJwAAAC0AAAA2AA' ... 'AAOAAAADgAAAA3AAAAKQAAACYAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>Age=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('MQAAADAAAAAlAAAAOgAAADEAAAAmAA' ... 'A5AAAALQAAAEQAAAA5AAAAOQAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Age'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [36]:
px.pie(heart_df,names="HeartDisease",title="Percentage of H eartDisease classes distribution")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'HeartDisease=%{label}<extra></extra>',
              'labels': {'bdata': ('AAAAAAEAAAAAAAAAAQAAAAAAAAAAAA' ... 'AAAAEAAAABAAAAAQAAAAEAAAAAAAAA'),
                         'dtype': 'i4'},
              'legendgroup': '',
              'name': '',
              'showlegend': True,
              'type': 'pie'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Percentage of H eartDisease classes distribution'}}
})

In [37]:
px.histogram(heart_df,x="ChestPainType",color="HeartDisease")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ChestPainType=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAABAAAAAQAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAEAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ChestPainType=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AQAAAAIAAAACAAAAAAAAAAIAAAACAA' ... 'ACAAAAAwAAAAIAAAACAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ChestPainType'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [38]:
heart_df['RestingBP'].unique()

array([140, 160, 130, 138, 150, 120, 110, 136, 115, 100, 124, 113, 125,
       145, 112, 132, 118, 170, 142, 190, 135, 180, 108, 155, 128, 106,
        92, 200, 122,  98, 105, 133,  95,  80, 137, 185, 165, 126, 152,
       116, 144, 154, 134, 104, 139, 131, 141, 178, 146, 158, 123, 102,
        96, 143, 172, 156, 114, 127, 101, 174,  94, 148, 117, 192, 129,
       164], dtype=int32)

In [39]:
px.sunburst(heart_df,path=['HeartDisease','RestingBP'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'branchvalues': 'total',
              'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'labels=%{label}<br>count=%{value}<br>parent=%{parent}<br>id=%{id}<extra></extra>',
              'ids': array(['0/140', '1/160', '0/130', '1/138', '0/150', '0/120', '0/110', '1/140',
                            '1/136', '0/115', '1/110', '1/100', '1/120', '0/100', '0/124', '1/150',
                            '0/113', '0/125', '1/145', '1/125', '1/130', '0/112', '0/160', '1/112',
                            '0/132', '1/118', '1/170', '0/142', '0/190', '1/135', '1/180', '0/108',
                            '0/145', '1/115', '1/155', '1/128', '0/135', '0/180', '0/170', '1/106',
                            '1/92', '1/200', '1/122', '0/122', '0/98', '0/105', '0/133', '1/95',
                            '1/105', '0/155', '0/80', '1/137', '1/185', '1/165', '1/132', '1/142',
                            '0/126', '1/133', '0/152', '1/116', '0/138', '1/124', '1/144', '0/154',
                            '1/134', '0/104', '1/139', '0/128', '1/131', '0/134', '1/152', '1/126',
                            '1/154', '1/141', '0/131', '1/178', '1/146', '1/158', '0/106', '0/136',
                            '0/123', '1/102', '1/96', '0/139', '1/143', '1/104', '1/172', '1/156',
                            '0/118', '1/190', '0/114', '1/127', '0/101', '1/174', '1/108', '0/156',
                            '0/94', '0/148', '0/178', '1/117', '1/192', '1/123', '0/129', '0/102',
                            '0/172', '0/146', '1/148', '1/114', '1/164', '0', '1'], dtype=object),
              'labels': array(['140', '160', '130', '138', '150', '120', '110', '140', '136', '115',
                               '110', '100', '120', '100', '124', '150', '113', '125', '145', '125',
                               '130', '112', '160', '112', '132', '118', '170', '142', '190', '135',
                               '180', '108', '145', '115', '155', '128', '135', '180', '170', '106',
                               '92', '200', '122', '122', '98', '105', '133', '95', '105', '155', '80',
                               '137', '185', '165', '132', '142', '126', '133', '152', '116', '138',
                               '124', '144', '154', '134', '104', '139', '128', '131', '134', '152',
                               '126', '154', '141', '131', '178', '146', '158', '106', '136', '123',
                               '102', '96', '139', '143', '104', '172', '156', '118', '190', '114',
                               '127', '101', '174', '108', '156', '94', '148', '178', '117', '192',
                               '123', '129', '102', '172', '146', '148', '114', '164', '0', '1'],
                              dtype=object),
              'name': '',
              'parents': array(['0', '1', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '1', '0',
                                '0', '1', '0', '0', '1', '1', '1', '0', '0', '1', '0', '1', '1', '0',
                                '0', '1', '1', '0', '0', '1', '1', '1', '0', '0', '0', '1', '1', '1',
                                '1', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '1', '1', '1',
                                '0', '1', '0', '1', '0', '1', '1', '0', '1', '0', '1', '0', '1', '0',
                                '1', '1', '1', '1', '0', '1', '1', '1', '0', '0', '0', '1', '1', '0',
                                '1', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1', '0', '0', '0',
                                '0', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '', ''],
                               dtype=object),
              'type': 'sunburst',
              'values': {'bdata': ('NAAiAEIABwAZAE0AGgA4AAoABAAgAA' ... 'ABAAEAAQACAAEAAQABAAEAAQCaAfwB'),
                         'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [40]:
px.histogram(heart_df,x='FastingBS',color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>FastingBS=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>FastingBS=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAEAAAAAAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'FastingBS'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [41]:
px.sunburst(heart_df,path=['HeartDisease','MaxHR'])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'branchvalues': 'total',
              'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'labels=%{label}<br>count=%{value}<br>parent=%{parent}<br>id=%{id}<extra></extra>',
              'ids': array(['0/172', '1/156', '0/98', '1/108', '0/122', '0/170', '0/142', '1/130',
                            '0/120', '1/99', '0/145', '1/140', '0/137', '0/150', '1/166', '0/165',
                            '1/125', '1/160', '0/164', '1/150', '0/138', '0/178', '0/112', '0/118',
                            '0/127', '0/114', '1/122', '0/154', '0/155', '1/87', '0/148', '0/130',
                            '1/100', '0/168', '1/120', '0/184', '1/170', '1/121', '1/98', '0/140',
                            '1/153', '0/134', '1/96', '0/174', '0/175', '0/144', '1/82', '1/145',
                            '0/135', '0/115', '1/128', '0/116', '0/160', '1/115', '1/94', '1/112',
                            '1/155', '0/110', '1/92', '0/180', '0/100', '1/152', '1/124', '0/106',
                            '0/124', '0/125', '0/185', '1/180', '0/139', '1/110', '0/190', '0/152',
                            '1/175', '0/146', '1/118', '1/158', '0/132', '0/176', '1/119', '0/188',
                            '0/162', '1/134', '1/135', '1/105', '0/90', '1/138', '0/136', '1/116',
                            '0/128', '0/158', '0/167', '0/129', '1/136', '1/102', '1/142', '1/143',
                            '1/103', '1/91', '1/126', '0/126', '0/156', '1/93', '1/127', '1/139',
                            '1/131', '1/149', '1/123', '1/182', '1/176', '1/154', '0/141', '1/148',
                            '1/77', '1/109', '1/133', '0/179', '1/144', '1/114', '1/113', '1/104',
                            '1/95', '1/72', '0/97', '1/117', '1/86', '1/63', '1/157', '1/83',
                            '1/60', '1/70', '1/163', '1/67', '1/78', '1/90', '0/99', '1/141',
                            '0/86', '1/84', '1/106', '1/111', '1/129', '0/133', '0/131', '1/80',
                            '1/165', '0/111', '0/107', '1/97', '0/161', '0/69', '0/80', '1/88',
                            '0/153', '1/132', '1/162', '1/73', '1/159', '0/96', '0/151', '0/105',
                            '0/121', '0/159', '0/181', '0/143', '0/157', '0/186', '1/181', '0/163',
                            '1/177', '0/173', '0/169', '0/171', '0/149', '1/147', '1/169', '1/168',
                            '1/71', '1/161', '0/192', '0/182', '1/195', '1/173', '1/174', '1/146',
                            '0/194', '0/147', '1/171', '0/187', '0/166', '0/202', '0/123', '1/164',
                            '0', '1'], dtype=object),
              'labels': array(['172', '156', '98', '108', '122', '170', '142', '130', '120', '99',
                               '145', '140', '137', '150', '166', '165', '125', '160', '164', '150',
                               '138', '178', '112', '118', '127', '114', '122', '154', '155', '87',
                               '148', '130', '100', '168', '120', '184', '170', '121', '98', '140',
                               '153', '134', '96', '174', '175', '144', '82', '145', '135', '115',
                               '128', '116', '160', '115', '94', '112', '155', '110', '92', '180',
                               '100', '152', '124', '106', '124', '125', '185', '180', '139', '110',
                               '190', '152', '175', '146', '118', '158', '132', '176', '119', '188',
                               '162', '134', '135', '105', '90', '138', '136', '116', '128', '158',
                               '167', '129', '136', '102', '142', '143', '103', '91', '126', '126',
                               '156', '93', '127', '139', '131', '149', '123', '182', '176', '154',
                               '141', '148', '77', '109', '133', '179', '144', '114', '113', '104',
                               '95', '72', '97', '117', '86', '63', '157', '83', '60', '70', '163',
                               '67', '78', '90', '99', '141', '86', '84', '106', '111', '129', '133',
                               '131', '80', '165', '111', '107', '97', '161', '69', '80', '88', '153',
                               '132', '162', '73', '159', '96', '151', '105', '121', '159', '181',
                               '143', '157', '186', '181', '163', '177', '173', '169', '171', '149',
                               '147', '169', '168', '71', '161', '192', '182', '195', '173', '174',
                               '146', '194', '147', '171', '187', '166', '202', '123', '164', '0', '1'],
                              dtype=object),
              'name': '',
              'parents': array(['0', '1', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1', '0', '0',
                                '1', '0', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0',
                                '0', '1', '0', '0', '1', '0', '1', '0', '1', '1', '1', '0', '1', '0',
                                '1', '0', '0', '0', '1', '1', '0', '0', '1', '0', '0', '1', '1', '1',
                                '1', '0', '1', '0', '0', '1', '1', '0', '0', '0', '0', '1', '0', '1',
                                '0', '0', '1', '0', '1', '1', '0', '0', '1', '0', '0', '1', '1', '1',
                                '0', '1', '0', '1', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1',
                                '1', '0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1',
                                '1', '1', '1', '0', '1', '1', '1', '1', '1', '1', '0', '1', '1', '1',
                                '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0', '1', '1', '1',
                                '1', '0', '0', '1', '1', '0', '0', '1', '0', '0', '0', '1', '0', '1',
                                '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0',
                                '1', '0', '0', '0', '0', '1', '1', '1', '1', '1', '0', '0', '1', '1',
                                '1', '1', '0', '0', '1', '0', '0', '0', '0', '1', '', ''], dtype=object),
              'type': 'sunburst',
              'values': {'bdata': ('CgAGAAIACAAFAA4ACQAWAAsABgAFAB' ... 'ABAAIAAQABAAIAAQABAAEAmgH8AQ=='),
                         'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [42]:
px.violin(heart_df,x="HeartDisease",y="MaxHR",color="HeartDisease")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'HeartDisease=%{x}<br>MaxHR=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa'},
              'name': '0',
              'offsetgroup': '0',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('rAAAAGIAAAB6AAAAqgAAAKoAAACOAA' ... 'AAowAAAKkAAACmAAAAtgAAAK0AAAA='),
                    'dtype': 'i4'},
              'y0': ' ',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'HeartDisease=%{x}<br>MaxHR=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B'},
              'name': '1',
              'offsetgroup': '1',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': True,
              'type': 'violin',
              'x': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'ABAAAAAQAAAAEAAAABAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'x0': ' ',
              'xaxis': 'x',
              'y': {'bdata': ('nAAAAGwAAACCAAAAYwAAAIwAAACmAA' ... 'B7AAAAhAAAAI0AAABzAAAArgAAAA=='),
                    'dtype': 'i4'},
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'violinmode': 'overlay',
               'xaxis': {'anchor': 'y',
                         'categoryarray': [0, 1],
                         'categoryorder': 'array',
                         'domain': [0.0, 1.0],
                         'title': {'text': 'HeartDisease'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'MaxHR'}}}
})

In [43]:
px.histogram(heart_df,x='ST_Slope',color="HeartDisease")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ST_Slope=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAIAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ST_Slope=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'ABAAAAAQAAAAEAAAABAAAAAQAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ST_Slope'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [44]:
px.histogram(heart_df,x="ExerciseAngina",color='HeartDisease')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'HeartDisease=0<br>ExerciseAngina=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ... 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'bingroup': 'x',
              'hovertemplate': 'HeartDisease=1<br>ExerciseAngina=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': '1',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('AAAAAAEAAAABAAAAAQAAAAEAAAAAAA' ... 'ABAAAAAAAAAAAAAAABAAAAAAAAAA=='),
                    'dtype': 'i4'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'HeartDisease'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'ExerciseAngina'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [ ]:
px.histogram(heart_df,x="Exercse")